### ISSUE TITLE
Paper 

### ISSUE THREAD

**Issue by dlc2017** [bencmbrook/Grammar-Checker#1]
Hi, this is a quit interesting project. Have you summarised it into manuscript, or would you recommend any related work? Thanks.

**Comment by bencmbrook** [comment]
@dlc2017 yup for sure. Just uploaded it. And there's a shorter summary on the poster which is now on the main repo page. Also check out the citations at the end of the paper, they're very good

The paper:
https://github.com/bencmbrook/Grammar-Checker/blob/master/Grammar%20Checker%20Using%20Hidden%20Markov%20Models%20and%20Trained%20CFGs.pdf
